import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import MarqueeBanner from "@/components/MarqueeBanner";
import CoffeeProvider from "@/context/CoffeeContext";

const mont = Montserrat({
  weight: "200",
  style: "normal",
  subsets: ["vietnamese"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MarqueeBanner />
        <NavBar className={mont} />
        <CoffeeProvider>{children}</CoffeeProvider>
        <Footer />
      </body>
    </html>
  );
}
