import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import MarqueeBanner from "@/components/MarqueeBanner";
import CoffeeProvider from "@/context/CoffeeContext";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/components/FontFamily";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <MarqueeBanner />
          <NavBar />
          <CoffeeProvider>{children}</CoffeeProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
