import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import CoffeeCup from "@/components/CoffeeCup";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";

const mont = Montserrat({
  weight: "200",
  style: "normal",
  subsets: ["vietnamese"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Marquee />
        <NavBar className={mont} />
        <CoffeeCup />
        <Footer />
      </body>
    </html>
  );
}
